"""
Django settings for ephany_framework project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from corsheaders.defaults import default_headers

# Load .env using an explicit path anchored to this file's location,
# so it works regardless of the working directory the server is started from.
load_dotenv(Path(__file__).resolve().parent.parent.parent / '.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-fallback-key-for-dev-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,ephany.io,.ephany.io').split(',')

# CSRF trusted origins
CSRF_TRUSTED_ORIGINS = os.environ.get(
    'CSRF_TRUSTED_ORIGINS',
    'https://ephany.io,https://*.ephany.io'
).split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Local apps
    'access',
    'assets',
    'projects',
    'users',
    # Third party apps
    'corsheaders',
    'django_filters',
    'drf_spectacular',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'access.middleware.APIKeyMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ephany_framework.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ephany_framework.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# REST API settings
REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        # For file uploads:
        'rest_framework.parsers.MultiPartParser',  # Handles the file
        'rest_framework.parsers.FormParser',  # Handles the form data
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # Checks "Authorization: Token <key>"
        'rest_framework.authentication.SessionAuthentication',  # For browser admin access
    ],

    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated', # Lock down API by default (optional but recommended)
        'access.permissions.HasAPIKeyOrAuthenticated',
    ],

    # Generates the OpenAPI 3 schema served at /api/schema/
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_METADATA_CLASS": "rest_framework.metadata.SimpleMetadata",
    "DEFAULT_PAGINATION_CLASS": "ephany_framework.pagination.StandardResultsSetPagination",
    "PAGE_SIZE": 50,
}

# --- OpenAPI schema ---------------------------------------------------------
# Generated by drf-spectacular and served at /api/schema/, with browsable
# documentation at /api/docs/ (Swagger UI) and /api/redoc/ (ReDoc).
# Regenerate the committed openapi.yaml with:
#   python manage.py spectacular --file openapi.yaml
SPECTACULAR_SETTINGS = {
    "TITLE": "Ephany Framework API",
    "DESCRIPTION": """Track a standard kit of parts across a fleet of near-identical projects.

The core chain is **Asset** (catalog definition) -> **Project** -> **Snapshot**
(a point in time) -> **AssetInstance** (one occurrence of a catalog asset in
that snapshot). Assets may be assemblies composed of other assets, and both
assets and instances carry `custom_fields` validated against the
`AssetAttribute` schema.""",
    "VERSION": "0.1.0",
    # The schema view serves the spec itself; it should not appear in the spec.
    "SERVE_INCLUDE_SCHEMA": False,
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
    "COMPONENT_SPLIT_REQUEST": True,
    "SORT_OPERATIONS": True,
    "SCHEMA_PATH_PREFIX": "/api",
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
        "displayRequestDuration": True,
    },
    # The X-API-Key scheme is enforced by access.middleware.APIKeyMiddleware
    # rather than a DRF authentication class, so drf-spectacular cannot detect
    # it automatically. Declare it here so it appears in the schema and in the
    # Swagger UI "Authorize" dialog.
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "ApiKeyAuth": {
                "type": "apiKey",
                "in": "header",
                "name": "X-API-Key",
                "description": (
                    "Required on /api/ routes when API_KEY_AUTH_ENABLED is "
                    "true. Create a key with: "
                    "python manage.py create_apikey \"Local Dev\""
                ),
            }
        }
    },
    "SECURITY": [{"ApiKeyAuth": []}],
    "TAGS": [
        {"name": "assets", "description": "The catalog: what a thing is."},
        {"name": "projects", "description": "The fleet: where things are installed."},
        {"name": "access", "description": "API keys and authentication."},
        {"name": "users", "description": "User accounts."},
    ],
}

API_KEY_AUTH_ENABLED = os.getenv("API_KEY_AUTH_ENABLED", "False").lower() == "true"

# All paths starting with any of these prefixes will require an API key when enabled
API_KEY_PROTECTED_PREFIXES = [
    "/api/",
]
# These paths are exempt from requiring an API key.
# The schema and docs routes describe the API's shape but expose no records.
# Remove them here if you would rather keep the documentation private too.
API_KEY_EXEMPT_PATHS = [
    "/api/login/",
    "/api/token-auth/",
    "/api/schema/",
    "/api/docs/",
    "/api/redoc/",
]

# --- Smartsheet integration -------------------------------------------------
# Optional. Only used by the `sync_projects_from_smartsheet` and
# `sync_project_snapshots` management commands. Leave unset if you do not use
# Smartsheet; the commands will tell you which variable to set.
#
# SMARTSHEET_PROJECTS_SHEET_ID  Sheet holding one row per project.
# SMARTSHEET_SNAPSHOTS_FOLDER_ID  Folder of per-snapshot asset sheets.
# SMARTSHEET_LOOKUP_SHEET_ID    Sheet mapping Project ID -> project name.
#                               Defaults to SMARTSHEET_PROJECTS_SHEET_ID.
SMARTSHEET_PROJECTS_SHEET_ID = os.getenv('SMARTSHEET_PROJECTS_SHEET_ID', '')
SMARTSHEET_SNAPSHOTS_FOLDER_ID = os.getenv('SMARTSHEET_SNAPSHOTS_FOLDER_ID', '')
SMARTSHEET_LOOKUP_SHEET_ID = os.getenv(
    'SMARTSHEET_LOOKUP_SHEET_ID',
    SMARTSHEET_PROJECTS_SHEET_ID,
)

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite dev server
    "https://ephany.io",
    "https://framework.ephany.io",
    "http://localhost:3000"
]

CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-api-key",
    "authorization"
]
