# Generated by Django 6.0 on 2025-12-06 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_unit', models.CharField(choices=[('mm', 'Millimeters (mm)'), ('cm', 'Centimeters (cm)'), ('m', 'Meters (m)'), ('in', 'Inches (in)'), ('ft', 'Feet (ft)')], default='mm', max_length=10)),
                ('area_unit', models.CharField(choices=[('sq_m', 'Square Meters (m²)'), ('sq_ft', 'Square Feet (ft²)')], default='sq_m', max_length=10)),
                ('volume_unit', models.CharField(choices=[('cu_m', 'Cubic Meters (m³)'), ('cu_ft', 'Cubic Feet (ft³)')], default='cu_m', max_length=10)),
                ('mass_unit', models.CharField(choices=[('kg', 'Kilograms (kg)'), ('lb', 'Pounds (lb)')], default='kg', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
