# Generated by Django 6.0 on 2025-12-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='unique_id',
            new_name='job_id',
        ),
    ]
