# Generated by Django 6.0 on 2025-12-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_unique_id_project_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='job_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Job ID'),
        ),
    ]
