# Generated by Django 6.0 on 2025-12-17 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options_alter_snapshot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
