# Generated by Django 6.0 on 2025-12-18 06:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_vendor_assetattribute_scope_vendorproduct'),
        ('projects', '0005_alter_snapshot_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snapshot',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='snapshot',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='If True, instances within this snapshot should be treated as read-only.'),
        ),
        migrations.AlterUniqueTogether(
            name='snapshot',
            unique_together={('project', 'name')},
        ),
        migrations.CreateModel(
            name='AssetInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineage_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('location', models.CharField(blank=True, help_text='Room, Floor, or Zone', max_length=100)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text="Key-value pairs matching 'instance' scoped AssetAttributes")),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_instances', to='assets.asset')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='projects.snapshot')),
            ],
            options={
                'ordering': ['location', 'asset__name'],
            },
        ),
    ]
