# Generated by Django 6.0 on 2025-12-18 06:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_vendor_assetattribute_scope_vendorproduct'),
        ('projects', '0006_alter_snapshot_options_snapshot_is_locked_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetinstance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='snapshot',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='snapshot',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='assetinstance',
            name='lineage_id',
        ),
        migrations.RemoveField(
            model_name='assetinstance',
            name='location',
        ),
        migrations.AddField(
            model_name='assetinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetinstance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='portfolio_img',
            field=models.ImageField(blank=True, null=True, upload_to='project_thumbnails/'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assetinstance',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='assetinstance',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='job_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='is_locked',
        ),
    ]
