# Generated by Django 6.0 on 2025-12-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_assetinstance_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinstance',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
