# Generated by Django 6.0 on 2025-12-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_assetinstance_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinstance',
            name='instance_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
