# Generated by Django 6.0 on 2026-01-16 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_assetcomponent_is_optional_and_more'),
        ('projects', '0009_assetinstance_instance_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetComponentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text="Quantity of this optional component for this specific instance. Defaults to the component's base quantity.")),
                ('asset_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='assets.assetcomponent', verbose_name='Asset Component')),
                ('asset_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_components', to='projects.assetinstance', verbose_name='Asset Instance')),
            ],
            options={
                'verbose_name': 'Asset Component Instance',
                'verbose_name_plural': 'Asset Component Instances',
                'ordering': ['asset_instance', 'asset_component'],
                'unique_together': {('asset_instance', 'asset_component')},
            },
        ),
    ]
