# Generated by Django 6.0 on 2026-03-20 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_assetcomponentinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100, unique=True, verbose_name='Site ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['site_id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='fc_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='go_live_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ri_model',
            field=models.CharField(blank=True, choices=[('app_delegated', 'App, Fully Delegated'), ('cce_delegated', 'CCE, Fully Delegated'), ('cce_integrated', 'CCE, Fully Integrated'), ('cce_order_delegated', 'CCE, Order Delegated'), ('cce_partial', 'CCE, Partially Delegated'), ('combo_cce', 'Combo (App + CCE, Fully Integrated)'), ('combo_ordering', 'Combo (APP + Ordering By Amazon)'), ('custom_sa', 'Custom - Requires SA Support'), ('oba_ca', 'Ordering by Amazon: CA'), ('oba_uk', 'Ordering by Amazon: UK'), ('oba_us', 'Ordering by Amazon: US'), ('oba_au', 'Ordering by Amazon: AU')], max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='State / Province'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue')], max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='trackable_area_planned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='trackable_area_designed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='vertical',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='vo_percentage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='VO %'),
        ),
        migrations.AddField(
            model_name='project',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='ZIP / Postal Code'),
        ),
        migrations.AddField(
            model_name='project',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.site'),
        ),
    ]
