# Generated by Django 6.0 on 2026-08-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_custom_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetinstance',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['job_id']},
        ),
        migrations.AlterModelOptions(
            name='snapshot',
            options={'ordering': ['-date', 'id']},
        ),
    ]
