# Generated by Django 6.0 on 2026-08-31 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0028_prototype_prototypeitem'),
        ('projects', '0013_alter_assetinstance_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='prototype',
            field=models.ForeignKey(blank=True, help_text='The standard this snapshot was built to. Leave empty for snapshots that are not measured against one.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='assets.prototype'),
        ),
    ]
