# Generated by Django 6.0 on 2025-12-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assets/files/')),
                ('category', models.CharField(choices=[('PDS', 'Cut Sheet'), ('CAD', 'CAD File'), ('RVT', 'Revit Family'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='assets', to='assets.assetfile'),
        ),
    ]
