# Generated by Django 6.0 on 2025-12-04 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assetfile_asset_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='url',
            field=models.URLField(blank=True, verbose_name='Product URL'),
        ),
    ]
