# Generated by Django 6.0 on 2025-12-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_uploaded_at_asset_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetfile',
            name='category',
            field=models.CharField(choices=[('PDS', 'Cut Sheet'), ('DWG', 'CAD File'), ('RFA', 'Revit Family'), ('OTH', 'Other')], default='OTH', max_length=3),
        ),
    ]
