# Generated by Django 6.0 on 2025-12-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_assetfile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='url',
            field=models.URLField(blank=True, verbose_name='Company Website'),
        ),
    ]
