# Generated by Django 6.0 on 2025-12-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_manufacturer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetfile',
            name='category',
            field=models.CharField(choices=[('PDS', 'Cut Sheet'), ('DWG', 'CAD File'), ('RFA', 'Revit Family'), ('ETC', 'Other')], default='ETC', max_length=3),
        ),
    ]
