# Generated by Django 6.0 on 2025-12-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_assetfile_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Define a valid key name for custom fields (e.g., 'Material', 'Finish', 'Color')", max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
