# Generated by Django 6.0 on 2025-12-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_assetattribute_asset_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetattribute',
            name='data_type',
            field=models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean')], default='str', help_text='Enforce a specific data type for this attribute', max_length=10),
        ),
    ]
