# Generated by Django 6.0 on 2025-12-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_assetattribute_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetattribute',
            name='name',
            field=models.CharField(help_text="Key name. Must be lowercase, use underscores, and have no special characters (e.g., 'material_finish').", max_length=50, unique=True),
        ),
    ]
