# Generated by Django 6.0 on 2025-12-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_assetattribute_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetattribute',
            name='data_type',
            field=models.CharField(choices=[('str', 'Text'), ('int', 'Whole Number'), ('float', 'Decimal Number'), ('bool', 'Yes / No')], default='str', help_text='Enforce a specific data type for this attribute', max_length=10),
        ),
    ]
