# Generated by Django 6.0 on 2025-12-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_alter_assetattribute_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='overall_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='overall_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='overall_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetattribute',
            name='unit_type',
            field=models.CharField(choices=[('none', 'No Unit (Text/Bool/Int)'), ('autodesk.spec.aec:length-2.0.0', 'Length'), ('autodesk.spec.aec:distance-1.0.0', 'Distance'), ('autodesk.spec.aec:area-2.0.0', 'Area'), ('autodesk.spec.aec:volume-2.0.0', 'Volume'), ('autodesk.spec.aec:mass-2.0.0', 'Mass / Weight'), ('autodesk.spec.aec:massDensity-2.0.0', 'Density'), ('autodesk.spec.aec:angle-2.0.0', 'Angle'), ('autodesk.spec.aec:slope-2.0.0', 'Slope'), ('autodesk.spec.aec:number-2.0.0', 'Number (Unitless)')], default='none', help_text='Revit SpecTypeId for unit conversion', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetattribute',
            name='data_type',
            field=models.CharField(choices=[('str', 'Text'), ('int', 'Whole Number'), ('float', 'Decimal'), ('bool', 'Yes / No')], default='str', help_text='Enforce a specific data type for this attribute', max_length=10),
        ),
    ]
