# Generated by Django 6.0 on 2025-12-07 18:47

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_asset_overall_depth_asset_overall_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='catalog_img',
            field=models.ImageField(blank=True, null=True, upload_to=assets.models.asset_catalog_img_path),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=assets.models.manufacturer_logo_path),
        ),
    ]
