# Generated by Django 6.0 on 2025-12-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_asset_catalog_img_manufacturer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(default='Delete Me', max_length=255),
            preserve_default=False,
        ),
    ]
