# Generated by Django 6.0 on 2025-12-08 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_assetcategory_asset_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetattribute',
            options={'ordering': ['name'], 'verbose_name_plural': 'Asset Attributes'},
        ),
        migrations.AlterModelOptions(
            name='assetfile',
            options={'verbose_name_plural': 'Asset Files'},
        ),
    ]
