# Generated by Django 6.0 on 2025-12-11 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_alter_assetattribute_options_alter_assetfile_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='unique_id',
            new_name='type_id',
        ),
    ]
