# Generated by Django 6.0 on 2025-12-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_rename_unique_id_asset_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Type ID'),
        ),
    ]
