# Generated by Django 6.0 on 2025-12-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_alter_asset_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
