# Generated by Django 6.0 on 2025-12-18 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_alter_asset_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='assetattribute',
            name='scope',
            field=models.CharField(choices=[('type', 'Asset Type (Catalog)'), ('instance', 'Asset Instance (Project)'), ('both', 'Both')], default='type', help_text='Determines if this field appears on the generic Catalog definition or the specific Project Instance.', max_length=20),
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, help_text="Vendor's internal SKU", max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Current market price', max_digits=12)),
                ('lead_time_days', models.PositiveIntegerField(default=0, help_text='Estimated lead time in days')),
                ('url', models.URLField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to='assets.asset')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='assets.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Product',
                'verbose_name_plural': 'Vendor Products',
                'unique_together': {('asset', 'vendor')},
            },
        ),
    ]
