# Generated by Django 6.0 on 2026-01-15 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_alter_assetattribute_data_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of this component required in the assembly')),
                ('child_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_assemblies', to='assets.asset', verbose_name='Component')),
                ('parent_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='assets.asset', verbose_name='Assembly')),
            ],
            options={
                'verbose_name': 'Asset Component',
                'verbose_name_plural': 'Asset Components',
                'ordering': ['parent_asset', 'child_asset'],
                'unique_together': {('parent_asset', 'child_asset')},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='component_assets',
            field=models.ManyToManyField(blank=True, help_text='Assets that are components of this assembly', related_name='parent_assemblies', through='assets.AssetComponent', through_fields=('parent_asset', 'child_asset'), to='assets.asset', verbose_name='Component Assets'),
        ),
    ]
