# Generated by Django 6.0 on 2026-01-16 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_assetcomponent_asset_component_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcomponent',
            name='is_optional',
            field=models.BooleanField(default=False, help_text='If True, this component is optional and can be added/removed per AssetInstance. If False, this component is required.'),
        ),
        migrations.AlterField(
            model_name='assetcomponent',
            name='child_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_assemblies', to='assets.asset', verbose_name='Child Asset (Component)'),
        ),
        migrations.AlterField(
            model_name='assetcomponent',
            name='parent_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='assets.asset', verbose_name='Parent Asset (Assembly)'),
        ),
        migrations.AlterField(
            model_name='assetcomponent',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of this component needed in the assembly'),
        ),
    ]
