# Generated by Django 6.0 on 2026-01-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_assetcomponent_is_optional_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetcomponent',
            old_name='quantity',
            new_name='quantity_required',
        ),
        migrations.RemoveField(
            model_name='assetcomponent',
            name='is_optional',
        ),
        migrations.AddField(
            model_name='assetcomponent',
            name='can_add_per_instance',
            field=models.BooleanField(default=False, help_text='If true, this component can have additional quantities added per AssetInstance (project-level).'),
        ),
    ]
