# Generated by Django 6.0 on 2026-03-12 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_rename_quantity_assetcomponent_quantity_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetattribute',
            name='data_type',
            field=models.CharField(choices=[('str', 'Text'), ('int', 'Whole Number'), ('float', 'Decimal'), ('bool', 'Yes / No'), ('choice', 'Choice')], default='str', help_text='Enforce a specific data type for this attribute.', max_length=10),
        ),
        migrations.CreateModel(
            name='AssetAttributeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Allowed value for this attribute. Must be unique within this attribute.', max_length=255, verbose_name='Choice Value')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assets.assetattribute', verbose_name='Asset Attribute')),
            ],
            options={
                'verbose_name': 'Asset Attribute Choice',
                'verbose_name_plural': 'Asset Attribute Choices',
                'ordering': ['attribute', 'value'],
                'unique_together': {('attribute', 'value')},
            },
        ),
    ]
