# Generated by Django 6.0 on 2026-03-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_alter_assetattribute_data_type_assetattributechoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetattributechoice',
            options={'ordering': ['attribute', 'order', 'value'], 'verbose_name': 'Asset Attribute Choice', 'verbose_name_plural': 'Asset Attribute Choices'},
        ),
        migrations.AddField(
            model_name='assetattributechoice',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order of this choice in the picklist (lower numbers appear first).'),
        ),
    ]
