# Generated by Django 6.0 on 2026-03-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_alter_assetattributechoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetattribute',
            name='data_type',
            field=models.CharField(choices=[('str', 'Text'), ('int', 'Whole Number'), ('float', 'Decimal'), ('bool', 'Yes / No'), ('choice', 'Picklist (Single)'), ('multi_choice', 'Picklist (Multiple)')], default='str', help_text='Enforce a specific data type for this attribute.', max_length=20),
        ),
    ]
