# Generated by Django 6.0 on 2026-08-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_alter_assetattribute_data_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['name', 'type_id']},
        ),
        migrations.AlterModelOptions(
            name='assetattributechoice',
            options={'ordering': ['attribute', 'order', 'value', 'id'], 'verbose_name': 'Asset Attribute Choice', 'verbose_name_plural': 'Asset Attribute Choices'},
        ),
        migrations.AlterModelOptions(
            name='assetfile',
            options={'ordering': ['-uploaded_at', 'id'], 'verbose_name_plural': 'Asset Files'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='vendorproduct',
            options={'ordering': ['id'], 'verbose_name': 'Vendor Product', 'verbose_name_plural': 'Vendor Products'},
        ),
    ]
