# Generated by Django 6.0 on 2026-08-31 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0027_alter_asset_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Identifies the standard across its versions, e.g. 'RTL-STD'.", max_length=50)),
                ('version', models.CharField(help_text="Revision of that standard, e.g. '2024.1'.", max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Clear this on a superseded version to keep it out of pickers. It stays valid for the snapshots already built to it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code', 'version', 'id'],
                'unique_together': {('code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PrototypeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='How many this standard calls for.')),
                ('is_required', models.BooleanField(default=True, help_text='Clear for parts that are site-dependent rather than standard. Absence of an optional item is not drift.')),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prototype_items', to='assets.asset')),
                ('prototype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.prototype')),
            ],
            options={
                'verbose_name': 'Prototype Item',
                'verbose_name_plural': 'Prototype Items',
                'ordering': ['prototype', 'asset', 'id'],
                'unique_together': {('prototype', 'asset')},
            },
        ),
    ]
